# Generated by Django 6.0 on 2025-12-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_accessory_innerwear_rentalitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="box_items",
            field=models.JSONField(
                blank=True, help_text="Items included in the product box", null=True
            ),
        ),
    ]
