# Generated by Django 6.0 on 2025-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_box_items"),
    ]

    operations = [
        migrations.RemoveField(model_name="rentalitem", name="size",),
        migrations.AddField(
            model_name="rentalitem",
            name="buy_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rentalitem",
            name="sizes",
            field=models.JSONField(default=[], help_text="Example: ['S','M','L','XL']"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="box_items",
            field=models.JSONField(
                blank=True,
                help_text="Example: ['Shirt fabric', 'Dhoti', 'Angavastram']",
                null=True,
            ),
        ),
    ]
