# Generated by Django 6.0 on 2025-12-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_rentalitem_size_rentalitem_buy_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rentals/")),
                (
                    "rental_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.rentalitem",
                    ),
                ),
            ],
        ),
    ]
