# Generated by Django 6.0 on 2025-12-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rentalimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabric",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="fabrics/"),
        ),
    ]
