# Generated by Django 6.0 on 2025-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("fabric_only", "Fabric Only"),
                    ("fabric_with_stitching", "Fabric With Stitching"),
                    ("ready_made", "Ready-made"),
                    ("rental", "Rental"),
                    ("accessory", "Accessory"),
                ],
                default="ready_made",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
