# Generated by Django 6.0 on 2025-12-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
