# Generated by Django 6.0 on 2025-12-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order", options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(model_name="order", name="order_type",),
    ]
