# Generated by Django 6.0 on 2025-12-19 15:34

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    STATUS_MAP = {
        "confirmed": "processing",
        "in_production": "stitching",
        "ready": "ready_for_pickup",
        "completed": "picked_up",
    }

    for order in Order.objects.all():
        if order.status in STATUS_MAP:
            order.status = STATUS_MAP[order.status]
            order.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_options_remove_order_order_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("placed", "Placed"),
                    ("processing", "Processing"),
                    ("stitching", "Stitching"),
                    ("buttoning", "Buttoning"),
                    ("ironing", "Ironing"),
                    ("ready_for_pickup", "Ready for Pickup"),
                    ("picked_up", "Picked Up"),
                    ("returned", "Returned"),
                    ("deposit_refunded", "Deposit Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                default="placed",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_old_statuses),
    ]
