# Generated by Django 6.0 on 2025-12-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("fabric_only", "Fabric Only"),
                    ("fabric_with_stitching", "Fabric With Stitching"),
                    ("ready_made", "Ready-made"),
                    ("rental", "Rental"),
                    ("rental_buy", "Rental Buy"),
                    ("accessory", "Accessory"),
                    ("innerwear", "Innerwear"),
                    ("traditional", "Traditional"),
                ],
                default="ready_made",
                max_length=30,
            ),
        ),
    ]
