# Generated by Django 6.0 on 2025-12-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_rental_item_alter_order_product"),
        ("products", "0008_alter_fabric_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="products.accessory",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="innerwear",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="products.innerwear",
            ),
        ),
    ]
